  
language: node_js
node_js:
  - "11"
dist: trusty
env:
  - NODE_ENV=ci PORT=3000
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm install
  - npm run build
script:
  - npm run check
  - npm run build
  - npm run test